Imu driver
Northeastern-Electric-Racing/Cerberus pull request #12
Opened 2023-06-13 23:40 UTC by HamzaIqbal69

Filled in IMU driver

2023-06-14 23:00 UTC, nwdepatie requested changes
Overall I am really impressed. I would merge it in now but there's some minor fixes I want you to think about. I think one more revision and we can squash and merge

2023-06-14 23:00 UTC, nwdepatie commented on Drivers/imu/imu.c
> +uint8_t imu_init(IMU_DATA *imu, I2C_HandleTypeDef *i2cHandle)
I think you forgot to rename some of your parameters, since it still says IMU_DATA. Also do i2c_handle

2023-06-14 23:03 UTC, HamzaIqbal69 commented on Drivers/imu/imu.h
> +#define LSM6D_REG_WHO_AM_I              0x0F    /* Register for checking communication */
Thats the actual name but i can change that

2023-06-14 23:04 UTC, HamzaIqbal69 commented on Drivers/imu/imu.c
> +        return 255;
I just used that arbitrarily as a fault code, I could enum it

2023-06-14 23:36 UTC, HamzaIqbal69 commented on Drivers/imu/imu.c
> +    int8_t lp_f2_enable_accel = 0x01;
not sure how to make this work since I need it to be an 8 bit integer

2023-06-20 23:19 UTC, nwdepatie commented on Drivers/imu/imu.c
> +uint8_t LSM6D_init(IMU_DATA *imu, I2C_HandleTypeDef *i2cHandle)
Still an IMU_DATA :(

2023-06-21 02:47 UTC, nwdepatie approved these changes
I'm approving since I made the changes I wanted lol

2023-06-21 02:51 UTC, nwdepatie commented
I was lazy and forgot to separate the commits for generating the STM32 HAL code and writing the driver, in the future I'll try and separate those into different commits

2023-06-21 02:56 UTC, merged