#141 Add Torque Calcs MVP (Unvalidated)
Northeastern-Electric-Racing/Cerberus pull request #146
Opened 2024-04-03 20:21 UTC by Peyton-McKee

## Changes

Added Torque Calcs for different drive states. Added computation for translated ERPM to RPM and RPM to MPH for torque limiting. Converted C++ code to hopefully working c code from old cerb. Added Torque limiting inputs via paddles when in efficiency mode 

## To Do

regen still needs to be done if were gonna try that 

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please reach out to your Project Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #141  (issue #)

2024-04-04 18:01 UTC, nwdepatie requested changes
TODO:
- Add comments to torque calc so its easier to figure out what is going on
- Make DTI a struct you pass around to act as an "object", this implementation limits us to only ever having 1 motor controller
- make functions for button callbacks based on state

2024-04-04 18:04 UTC, Peyton-McKee commented on Core/Src/dti.c
> +	dti = mc;
ah ok that makes more sense i was confused with what was going on.

2024-04-04 19:00 UTC, nwdepatie requested changes
Change accumulator to be static inside of a function, also we need to test so I won't approve until it is somehow tested

2024-04-04 19:00 UTC, nwdepatie commented on Core/Src/torque.c
> +		memcpy(torque_accumulator, temp, ACCUMULATOR_SIZE); // Copy the old values to the new array and shift them by one
THis memcpy moving average is kinda dope ngl

2024-04-04 19:00 UTC, nwdepatie commented on Core/Src/torque.c
> +static uint16_t torque_accumulator[ACCUMULATOR_SIZE];
I would recommend making this a static variable _inside_ the function for calcs. This limits the namespace of the variable to only inside that function AND it exists for the lifetime of the program

2024-04-04 19:00 UTC, nwdepatie commented on Core/Src/torque.c
> +void increase_torque_limit()
nit: maybe move these up in the file, I like the task to be at the very bottom so it is easy to find

2024-04-11 21:01 UTC, nwdepatie approved these changes
looks solid

2024-04-11 21:12 UTC, merged