SHT30 driver integration
Northeastern-Electric-Racing/Cerberus pull request #214
Opened 2024-10-20 20:19 UTC by marvin-g-personal

## Changes

- updated Cerberus to work with the new sht 

## Notes

- kept major code the same

## To Do

- should be done

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please reach out to your Project Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No merge conflicts
- [ ] All checks passing
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #160)

2024-10-20 20:46 UTC, marvin-g-personal commented
is the build failing because embedded base hadn't been updated with the new sht?

2024-10-24 21:07 UTC, dyldonahue requested changes

2024-10-24 21:07 UTC, dyldonahue commented on Core/Src/monitor.c
> +		if (read_temp_sensor(mpu, &temp, &humidity) != 0) {
previous convention is better, please do not change style conventions unless its part of the ticket

2024-10-24 21:07 UTC, dyldonahue commented on Core/Src/mpu.c
> +	mpu->temp_sensor.i2c_handle = hi2c;
based on ur (correct) change to the driver, there is no i2c handle in this struct anymore, so this needs to be removed

2024-10-24 21:07 UTC, dyldonahue commented on Core/Src/mpu.c
> +	mpu->temp_sensor.mem_read = (Mem_Read_Ptr)HAL_I2C_Mem_Read;
this wont work. The signature for the HAL functions is different than the function pointers you created. Youll need to create wrappers for them. Take a look at Caios work with the lsm driver

2024-10-24 21:07 UTC, dyldonahue commented on Core/Src/mpu.c
> +	if (hal_stat != HAL_OK)
again, please dont change this convention. (PS - it sort of becomes totally obvious that ur just putting this stuff through AI when arbitrary changes like this - in a completely different spot than any relevant changes u made - appear) Our code is open sourced so its whatever, but u can get in huge trouble with any employers for doing that with proprietary code. If im way off base my fault, but based on some changes here and in the embedded pr i assume i am not

2024-10-24 21:09 UTC, dyldonahue commented
in general, yes this build check is going to fail bc it refrecnes embedded base without ur changes. But there are still mistakes that would cause it to fail with urd atm. You should always try building locally with ur embedded base commit - I cant imagine this builds locally bc of that i2c handle member that no longer exists

2024-11-04 00:41 UTC, marvin-g-personal commented
I created a new branch that has the current changes caio made from develop since I made my original one in main; this is prevent merge conflict issues I'll name the new PR the same thing; mb.

2024-11-04 00:41 UTC, closed without merging