Feature/soc
Northeastern-Electric-Racing/Cerberus pull request #238
Opened 2024-12-02 20:12 UTC by harrison-e

## Changes

- Added LV Sense SoC calculation using logistic function to `Core/Src/monitor.c`
- Added `#include <math.h>` to `Core/Src/monitor.c`
- Changed CAN spec in `mpu.json` to include SOC NetField in `0x503` (See https://github.com/Northeastern-Electric-Racing/Embedded-Base/pull/212)

Closes #219

2024-12-02 20:14 UTC, harrison-e commented
Note that a better version of this uses Coulomb counting!

2024-12-04 05:19 UTC, jr1221 requested changes
see question about soc scale over CAN.

2024-12-04 05:19 UTC, jr1221 commented on Core/Src/monitor.c
> +	float k = -8.5; // logistic fn parameter to affect steepness of curve
label parts of algo `static const` if they do not change for readability sake, altough the compiler will optimize this stuff away anyways.

2024-12-04 05:19 UTC, jr1221 commented on Core/Src/monitor.c
> +	soc_int = soc_dec * 100;
so we apply a 100 scale to this 0 to 1 value, so the data sent over CAN is casted 0 to 100.  We can do to things to clarify this:
- Add a prescaler and corresponding JSON postscaler which allows us to get decimal points out of our SoC
- Or: Use a uint8_t instead as this is a number 0 to 100 so mine as well save space.

2024-12-06 04:05 UTC, jr1221 approved these changes
Lgtm.  Obv math may not work but the framework is there so that's good.

2024-12-08 22:08 UTC, merged