#52 Monitor Pedals
Northeastern-Electric-Racing/Cerberus pull request #77
Opened 2023-10-23 22:38 UTC by Peyton-McKee

pedal go brrr

closes #52

2023-10-23 22:41 UTC, nwdepatie commented
lmao peyton ticket

2023-10-24 00:01 UTC, nwdepatie requested changes
Overall this is essentially exactly what I was looking for which is great. In a future ticket we can handle faulting conditions just to get this merged in ASAP. Just make the small changes I suggested and then we good

2023-10-24 00:01 UTC, nwdepatie commented on Core/Src/monitor.c
> +	uint32_t adc_data[4];
Also double check resolution on STM ADC's, I know the teensy's were like 12 bit max, so we might be able to get away with `uint16_t`

2023-10-24 01:24 UTC, Peyton-McKee commented on Core/Src/main.c
> +  pedal_monitor_handle = osThreadNew(vPedalMonitor, &hi2c2, &pedal_monitor_attributes);
oh right

2023-10-24 19:17 UTC, nwdepatie commented
This builds now, but at what cost

2023-10-27 18:06 UTC, nwdepatie approved these changes
Going to approve so that we can enable some other tickets

2023-10-27 18:06 UTC, merged