49 dispatch task
Northeastern-Electric-Racing/Cerberus pull request #85
Opened 2023-10-28 00:27 UTC by Sabramz

2023-10-28 00:28 UTC, Sabramz commented on Drivers/Embedded-Base
I have no clue why this happened.

2023-11-02 19:02 UTC, nwdepatie requested changes
disapproved !

2023-11-02 23:07 UTC, Sabramz commented on Core/Src/can_handler.c
> +// what the hell is this
whoops

2023-11-03 15:27 UTC, nwdepatie approved these changes
I think this should be an okay start, we def need to handle faults in this task but that can be another ticket I'll make

2023-11-03 15:28 UTC, merged