fault handler attempt
Northeastern-Electric-Racing/Cerberus pull request #93
Opened 2023-11-06 19:05 UTC by Rand-Sai

I modified the "fault.c" file, attempted to use a if loop to pop faults off the queue and made a switch statement to create priorities for tasks.

2023-11-06 20:30 UTC, nwdepatie requested changes
Okay so there is def a bit of work to be done, but solid first attempt. I think I've sent a few reference commits but the typical flow of adding a task is:
1. create a function with similar parameters to the other `vSomething` tasks in other files (particularly monitor.c)
2. create a threadattributes struct, similar to the stuff implemented in monitor.h. These specify the attributes of each task
3. Actually initialize the task in main.c, there is a bunch of functions grouped together in main that are all initializing the task

2023-11-06 20:30 UTC, nwdepatie commented on Core/Src/fault.c
> +void priority(void) {
So this should be the main "task" which we will assign a priority and tell the kernel to schedule on boot. For references on other tasks, check the functions that start with `vSomething` in monitor.c. These have a thread attribute struct associated with them that we use to initialize in main.c

2023-11-06 20:30 UTC, nwdepatie commented on Core/Src/fault.c
> +    MSGQUEUE_OBJ_t msg;
So the type of the message that we receive depends on what we are actually queuing, in this case I believe the type is `FaultStatus_t` or something I forgot exactly what it is

2023-11-06 20:30 UTC, nwdepatie commented on Core/Src/fault.c
> +        id = osThreadGetId(); // Obtain ID of current running thread
You shouldn't need to get the ID each time

2023-11-06 20:30 UTC, nwdepatie commented on Core/Src/fault.c
> +        switch (fault_sev_t) {
You want to access the severity field of the `fault_t` or whatever data type you get from the queue. The idea is that we are popping off a fault and then routing to a case for the severity

2023-11-06 20:30 UTC, nwdepatie commented on Core/Src/fault.c
> +            osThreadSetPriority(id, osPriorityHigh);
I don't think we need to set the priority here, tbh I would just leave this blank for now apart from the `break;`'s and we will handle faults in a later ticket

2023-11-08 13:56 UTC, Rand-Sai commented
Made edits based on suggestions provided. Used functions from "https://www.keil.com/pack/doc/cmsis/RTOS2/html/group__CMSIS__RTOS__Message.html" as references.

2023-11-10 20:10 UTC, nwdepatie approved these changes
This looks like a solid start

2023-11-10 20:12 UTC, merged